---

- name: "Debug"
  vars:
    msg: |-
      ansible_os_family [{{ ansible_os_family }}]
      ansible_distribution [{{ ansible_distribution }}]
      ansible_distribution_major_version [{{ ansible_distribution_major_version }}]
      ansible_distribution_version [{{ ansible_distribution_version }}]
      ansible_distribution_release [{{ ansible_distribution_release }}]
      ansible_python_version [{{ ansible_python_version }}]

      rsnapshot_install [{{ rsnapshot_install }}]
      rsnapshot_test [{{ rsnapshot_test }}]
      rsnapshot_backup_conf [{{ rsnapshot_backup_conf }}]

      freebsd_install_method [{{ freebsd_install_method }}]
      freebsd_use_packages [{{ freebsd_use_packages }}]
      freebsd_install_retries [{{ freebsd_install_retries }}]
      freebsd_install_delay [{{ freebsd_install_delay }}]
      linux_install_retries [{{ linux_install_retries }}]
      linux_install_delay [{{ linux_install_delay }}]
      rsnapshot_packages
      {{ rsnapshot_packages|to_nice_yaml }}

      rsnapshot_config_version [{{ rsnapshot_config_version }}]
# TODO: Complete variables
#      rsnapshot_ [{{ rsnapshot_ }}]
#      rsnapshot_
#      {{ rsnapshot_|to_yaml }}
  ansible.builtin.debug:
    msg: "{{ msg.split('\n') }}"

# EOF
...
